// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icyjlgvsnhteothfnnap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljeWpsZ3Zzbmh0ZW90aGZubmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNzM1NDQsImV4cCI6MjA2Mjk0OTU0NH0.1d6vpuBFKwNfo0-pqZJbpakrqxxjyA2lL2zpYLgMKgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);